/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-31 05:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/Users/usonihs/Documents/Development/tomcat/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1664823970000L));
    _jspx_dependants.put("jar:file:/Users/usonihs/Documents/Development/tomcat/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<header\n");
      out.write("	class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom\">\n");
      out.write("	\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<a href = \"customerProductList.do\"><img src=\"sport-shoe.png\" style=\"width: 80px; margin-left: 30px;\" /></a>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function signup() {\n");
      out.write("	var form=document.loginbtn;\n");
      out.write("	form.action=\"http://localhost:8080/All100Shoes/Customer/customerSighup.jsp\";\n");
      out.write("	form.submit();\n");
      out.write("}</script>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-light\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link\" href=\"customerProductList.do\">All</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Nike\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductList.do?query=productbrand&content=nike\">Nike All</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=nike&pcategory=sneakers\">Sneakers</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=nike&pcategory=running\">Running</a></li>\n");
      out.write("            <!-- <li><hr class=\"dropdown-divider\"></li> -->\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=nike&pcategory=basketball\">Basketball</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Adidas\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductList.do?query=productbrand&content=nike\">Nike All</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=adidas&pcategory=sneakers\">Sneakers</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=adidas&pcategory=running\">Running</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=adidas&pcategory=basketball\">Basketball</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Underarmour\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductList.do?query=productbrand&content=nike\">Nike All</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=underarmour&pcategory=sneakers\">Sneakers</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=underarmour&pcategory=running\">Running</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=underarmour&pcategory=basketball\">Basketball</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <form class=\"d-flex\" role=\"search\" action=\"customerProductList.do\">\n");
      out.write("      	<select name=\"query\">\n");
      out.write("		<option value=\"productmodel\" selected=\"selected\">model</option>\n");
      out.write("		<option value=\"productbrand\">brand</option>\n");
      out.write("		</select>&nbsp;&nbsp;&nbsp;\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" name=\"content\">\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write(" \n");
      out.write("	<div class=\"col-md-4 text-end\" style=\"margin-right: 30px;\">\n");
      out.write("		");
if (session.getAttribute("CUSTOMERID") == null) { 
      out.write("\n");
      out.write("			<form name=\"loginbtn\" method=\"post\">\n");
      out.write("				<input type=\"button\" class=\"btn btn-outline-dark me-2\" onclick=\"login()\" value=\"Log in\"> \n");
      out.write("				<input type=\"button\" class=\"btn btn-dark me-2\" onclick=\"signup()\" value=\"Sign Up\">\n");
      out.write("			</form>\n");
      out.write("		");
} 
      out.write("\n");
      out.write("		\n");
      out.write("		");
if (session.getAttribute("CUSTOMERID") != null) { 
      out.write("\n");
      out.write("			<form name=\"loginokay\" method=\"post\" style=\"position: absolute; right: 0px; top: 30px;\">\n");
      out.write("				");
      out.print(session.getAttribute("CUSTOMERID") );
      out.write("님, 안녕하세요! \n");
      out.write("				<input type=\"submit\" class=\"btn btn-dark\" onclick=\"mypage()\" value=\"마이페이지\">\n");
      out.write("				<input type=\"submit\" class=\"btn btn-outline-dark me-2\" onclick=\"javascript: form.action='customerCartPage.do'\" value=\"장바구니\">\n");
      out.write("			</form>\n");
      out.write("			<div class=\"col-md-4 text-end\">\n");
      out.write("				<form name=\"loginokay\" method=\"post\" style=\"position: absolute; right: 0px; top: 70px;\">\n");
      out.write("					<input type=\"submit\" style=\"position: absolute; right: 85px;\" class=\"btn btn-outline-dark me-2\" onclick=\"javascript: form.action='customerBuyList.do'\" value=\"구매 리스트\">\n");
      out.write("					<input type=\"submit\" style=\"position: absolute; right: 10px;\" class=\"btn btn-dark\" onclick=\"javascript: form.action='login.do'\" value=\"로그아웃\">\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		");
} 
      out.write("\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
