/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-31 05:52:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/Users/usonihs/Documents/Development/tomcat/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1664823970000L));
    _jspx_dependants.put("/Customer/header.jsp", Long.valueOf(1667194494000L));
    _jspx_dependants.put("jar:file:/Users/usonihs/Documents/Development/tomcat/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/Customer/footer.jsp", Long.valueOf(1667149460000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; UTF-8;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
request.setCharacterEncoding("utf-8"); 
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.104.2\">\n");
      out.write("<title>All100Shoes</title>\n");
      out.write("\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.kr/docs/5.2/examples/product/\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function login() {\n");
      out.write("		var form = document.loginbtn;\n");
      out.write("		form.action = \"login.jsp\";\n");
      out.write("		form.submit();\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function logout() {\n");
      out.write("		var form = document.loginokay;\n");
      out.write("		form.action = \"main.jsp?id=null\";\n");
      out.write("		form.submit();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"/docs/5.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- Favicons -->\n");
      out.write("<link rel=\"shortcut icon\" href=\"sport-shoe.png\" sizes=\"180x180\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".bd-placeholder-img {\n");
      out.write("	font-size: 1.125rem;\n");
      out.write("	text-anchor: middle;\n");
      out.write("	-webkit-user-select: none;\n");
      out.write("	-moz-user-select: none;\n");
      out.write("	user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("	.bd-placeholder-img-lg {\n");
      out.write("		font-size: 3.5rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-divider {\n");
      out.write("	height: 3rem;\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\n");
      out.write("	border-width: 1px 0;\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\n");
      out.write("		rgba(0, 0, 0, .15);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-vr {\n");
      out.write("	flex-shrink: 0;\n");
      out.write("	width: 1.5rem;\n");
      out.write("	height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bi {\n");
      out.write("	vertical-align: -.125em;\n");
      out.write("	fill: currentColor;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller {\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 2;\n");
      out.write("	height: 2.75rem;\n");
      out.write("	overflow-y: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller .nav {\n");
      out.write("	display: flex;\n");
      out.write("	flex-wrap: nowrap;\n");
      out.write("	padding-bottom: 1rem;\n");
      out.write("	margin-top: -1px;\n");
      out.write("	overflow-x: auto;\n");
      out.write("	text-align: center;\n");
      out.write("	white-space: nowrap;\n");
      out.write("	-webkit-overflow-scrolling: touch;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<header\n");
      out.write("	class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom\">\n");
      out.write("	\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<a href = \"customerProductList.do\"><img src=\"sport-shoe.png\" style=\"width: 80px; margin-left: 30px;\" /></a>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function signup() {\n");
      out.write("	var form=document.loginbtn;\n");
      out.write("	form.action=\"http://localhost:8080/All100Shoes/Customer/customerSighup.jsp\";\n");
      out.write("	form.submit();\n");
      out.write("}</script>\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-light\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link\" href=\"customerProductList.do\">All</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Nike\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductList.do?query=productbrand&content=nike\">Nike All</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=nike&pcategory=sneakers\">Sneakers</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=nike&pcategory=running\">Running</a></li>\n");
      out.write("            <!-- <li><hr class=\"dropdown-divider\"></li> -->\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=nike&pcategory=basketball\">Basketball</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Adidas\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductList.do?query=productbrand&content=adidas\">Adidas All</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=adidas&pcategory=sneakers\">Sneakers</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=adidas&pcategory=running\">Running</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=adidas&pcategory=basketball\">Basketball</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Underarmour\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductList.do?query=productbrand&content=underarmour\">UnderArmour All</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=underarmour&pcategory=sneakers\">Sneakers</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=underarmour&pcategory=running\">Running</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"customerProductListCategory.do?pbrand=underarmour&pcategory=basketball\">Basketball</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <form class=\"d-flex\" role=\"search\" action=\"customerProductList.do\">\n");
      out.write("      	<select name=\"query\">\n");
      out.write("		<option value=\"productmodel\" selected=\"selected\">model</option>\n");
      out.write("		<option value=\"productbrand\">brand</option>\n");
      out.write("		</select>&nbsp;&nbsp;&nbsp;\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" name=\"content\">\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write(" \n");
      out.write("	<div class=\"col-md-4 text-end\" style=\"margin-right: 30px;\">\n");
      out.write("		");
if (session.getAttribute("CUSTOMERID") == null) { 
      out.write("\n");
      out.write("			<form name=\"loginbtn\" method=\"post\">\n");
      out.write("				<input type=\"button\" class=\"btn btn-outline-dark me-2\" onclick=\"login()\" value=\"Log in\"> \n");
      out.write("				<input type=\"button\" class=\"btn btn-dark me-2\" onclick=\"signup()\" value=\"Sign Up\">\n");
      out.write("			</form>\n");
      out.write("		");
} 
      out.write("\n");
      out.write("		\n");
      out.write("		");
if (session.getAttribute("CUSTOMERID") != null) { 
      out.write("\n");
      out.write("			<form name=\"loginokay\" method=\"post\" style=\"position: absolute; right: 0px; top: 30px;\">\n");
      out.write("				");
      out.print(session.getAttribute("CUSTOMERID") );
      out.write("님, 안녕하세요! \n");
      out.write("				<input type=\"submit\" class=\"btn btn-dark\" onclick=\"mypage()\" value=\"마이페이지\">\n");
      out.write("				<input type=\"submit\" class=\"btn btn-outline-dark me-2\" onclick=\"javascript: form.action='customerCartPage.do'\" value=\"장바구니\">\n");
      out.write("			</form>\n");
      out.write("			<div class=\"col-md-4 text-end\">\n");
      out.write("				<form name=\"loginokay\" method=\"post\" style=\"position: absolute; right: 0px; top: 70px;\">\n");
      out.write("					<input type=\"submit\" style=\"position: absolute; right: 85px;\" class=\"btn btn-outline-dark me-2\" onclick=\"javascript: form.action='customerBuyList.do'\" value=\"구매 리스트\">\n");
      out.write("					<input type=\"submit\" style=\"position: absolute; right: 10px;\" class=\"btn btn-dark\" onclick=\"javascript: form.action='login.do'\" value=\"로그아웃\">\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		");
} 
      out.write("\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("</header>");
      out.write("\n");
      out.write("\n");
      out.write("	<main>\n");
      out.write("		<div\n");
      out.write("			class=\"position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light enable-validation-icons-true\">\n");
      out.write("			<div\n");
      out.write("				class=\"col-md-5 p-lg-3 mx-auto my-5 enable-validation-icons-true\"\n");
      out.write("				style=\"background-image: 6.png; margin: -100%\">\n");
      out.write("				<h1 class=\"display-4 fw-normal\">All100Shoes</h1>\n");
      out.write("				<p class=\"lead fw-normal\" style=\"font-size: 0.9em\">별에도 별이 사람들의\n");
      out.write("					까닭입니다. 까닭이요, 잔디가 멀리 하나에 하나에 별들을 애기 때 나는 듯합니다. 사람들의 아무 봄이 그리워 많은 묻힌\n");
      out.write("					풀이 이국 계십니다. 시와 부끄러운 어머니, 못 걱정도 패, 당신은 우는 까닭입니다. 사랑과 않은 가을 봅니다. 오는\n");
      out.write("					나는 라이너 오면 하나 쓸쓸함과 별 거외다.</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"product-device shadow-sm d-none d-md-block\"></div>\n");
      out.write("			<div\n");
      out.write("				class=\"product-device product-device-2 shadow-sm d-none d-md-block\"></div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"d-md-flex flex-md-equal w-100 my-md-3 ps-md-3\">\n");
      out.write("			<div\n");
      out.write("				class=\"text bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden\">\n");
      out.write("				<div class=\"my-3 py-3\">\n");
      out.write("					<h2 class=\"display-5\">Lorem Ipsum</h2>\n");
      out.write("					<p class=\"lead\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("						adipiscing elit. Donec porttitor.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bg-light shadow-sm mx-auto\"\n");
      out.write("					style=\"width: 80%; height: 300px; border-radius: 21px 21px 0 0; background: #c5cae9\">\n");
      out.write("					<img src=\"1.png\" style=\"width: 90%\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div\n");
      out.write("				class=\"text bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden\">\n");
      out.write("				<div class=\"my-3 py-3\">\n");
      out.write("					<h2 class=\"display-5\">Lorem Ipsum</h2>\n");
      out.write("					<p class=\"lead\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("						adipiscing elit. Donec porttitor.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bg-light shadow-sm mx-auto\"\n");
      out.write("					style=\"width: 80%; height: 300px; border-radius: 21px 21px 0 0; background: #c5cae9\">\n");
      out.write("					<img src=\"2.png\" style=\"width: 90%\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div\n");
      out.write("				class=\"text bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden\">\n");
      out.write("				<div class=\"my-3 py-3\">\n");
      out.write("					<h2 class=\"display-5\">Lorem Ipsum</h2>\n");
      out.write("					<p class=\"lead\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("						adipiscing elit. Donec porttitor.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bg-light shadow-sm mx-auto\"\n");
      out.write("					style=\"width: 80%; height: 300px; border-radius: 21px 21px 0 0; background: #c5cae9\">\n");
      out.write("					<img src=\"3.png\" style=\"width: 90%\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"d-md-flex flex-md-equal w-100 my-md-3 ps-md-3\">\n");
      out.write("			<div\n");
      out.write("				class=\"text bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden\">\n");
      out.write("				<div class=\"my-3 py-3\">\n");
      out.write("					<h2 class=\"display-5\">Lorem Ipsum</h2>\n");
      out.write("					<p class=\"lead\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("						adipiscing elit. Donec porttitor.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bg-light shadow-sm mx-auto\"\n");
      out.write("					style=\"width: 80%; height: 300px; border-radius: 21px 21px 0 0; background: #c5cae9\">\n");
      out.write("					<img src=\"4.png\" style=\"width: 90%\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div\n");
      out.write("				class=\"text bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden\">\n");
      out.write("				<div class=\"my-3 py-3\">\n");
      out.write("					<h2 class=\"display-5\">Lorem Ipsum</h2>\n");
      out.write("					<p class=\"lead\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("						adipiscing elit. Donec porttitor.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bg-light shadow-sm mx-auto\"\n");
      out.write("					style=\"width: 80%; height: 300px; border-radius: 21px 21px 0 0; background: #c5cae9\">\n");
      out.write("					<img src=\"5.png\" style=\"width: 90%\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div\n");
      out.write("				class=\"text bg-light me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden\">\n");
      out.write("				<div class=\"my-3 py-3\">\n");
      out.write("					<h2 class=\"display-5\">Lorem Ipsum</h2>\n");
      out.write("					<p class=\"lead\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("						adipiscing elit. Donec porttitor.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"bg-light shadow-sm mx-auto\"\n");
      out.write("					style=\"width: 80%; height: 300px; border-radius: 21px 21px 0 0; background: #c5cae9\">\n");
      out.write("					<img src=\"6.png\" style=\"width: 90%\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("<footer\n");
      out.write("	class=\"d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark\">\n");
      out.write("	<div class=\"col-md-4 d-flex align-items-center bg-dark\">\n");
      out.write("		<a href=\"/\"\n");
      out.write("			class=\"mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1\"> </a>\n");
      out.write("		<span class=\"mb-3 mb-md-0 text-muted\">&copy; All100Shoes.inc</span>\n");
      out.write("	</div>\n");
      out.write("</footer>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\n");
      out.write("		integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js\"\n");
      out.write("		integrity=\"sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("		<!-- 부트스트랩 사용을 위한 준비 -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
