/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-28 15:09:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Customer/header.jsp", Long.valueOf(1666959187000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\"\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.104.2\">\n");
      out.write("<title>Product example · Bootstrap v5.2</title>\n");
      out.write("\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.2/examples/product/\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function login() {\n");
      out.write("		var form = document.loginbtn;\n");
      out.write("		form.action = \"login.jsp\";\n");
      out.write("		form.submit();\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function logout() {\n");
      out.write("		var form = document.loginokay;\n");
      out.write("		form.action = \"main.jsp?id=null\";\n");
      out.write("		form.submit();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<!-- Favicons -->\n");
      out.write("<link rel=\"apple-touch-icon\"\n");
      out.write("	href=\"/docs/5.2/assets/img/favicons/apple-touch-icon.png\"\n");
      out.write("	sizes=\"180x180\">\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.2/assets/img/favicons/favicon-32x32.png\"\n");
      out.write("	sizes=\"32x32\" type=\"image/png\">\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.2/assets/img/favicons/favicon-16x16.png\"\n");
      out.write("	sizes=\"16x16\" type=\"image/png\">\n");
      out.write("<link rel=\"manifest\" href=\"/docs/5.2/assets/img/favicons/manifest.json\">\n");
      out.write("<link rel=\"mask-icon\"\n");
      out.write("	href=\"/docs/5.2/assets/img/favicons/safari-pinned-tab.svg\"\n");
      out.write("	color=\"#712cf9\">\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.2/assets/img/favicons/favicon.ico\">\n");
      out.write("<meta name=\"theme-color\" content=\"#712cf9\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".bd-placeholder-img {\n");
      out.write("	font-size: 1.125rem;\n");
      out.write("	text-anchor: middle;\n");
      out.write("	-webkit-user-select: none;\n");
      out.write("	-moz-user-select: none;\n");
      out.write("	user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("	.bd-placeholder-img-lg {\n");
      out.write("		font-size: 3.5rem;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-divider {\n");
      out.write("	height: 3rem;\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\n");
      out.write("	border-width: 1px 0;\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\n");
      out.write("		rgba(0, 0, 0, .15);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".b-example-vr {\n");
      out.write("	flex-shrink: 0;\n");
      out.write("	width: 1.5rem;\n");
      out.write("	height: 100vh;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bi {\n");
      out.write("	vertical-align: -.125em;\n");
      out.write("	fill: currentColor;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller {\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 2;\n");
      out.write("	height: 2.75rem;\n");
      out.write("	overflow-y: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-scroller .nav {\n");
      out.write("	display: flex;\n");
      out.write("	flex-wrap: nowrap;\n");
      out.write("	padding-bottom: 1rem;\n");
      out.write("	margin-top: -1px;\n");
      out.write("	overflow-x: auto;\n");
      out.write("	text-align: center;\n");
      out.write("	white-space: nowrap;\n");
      out.write("	-webkit-overflow-scrolling: touch;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link href=\"product.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("<header\n");
      out.write("	class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom\">\n");
      out.write("	\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<img src=\"sport-shoe.png\" style=\"width: 80px\">\n");
      out.write("	<ul class=\"nav col-12 col-md-auto mb-2 justify-content-center mb-md-10\">\n");
      out.write("		<li><a href=\"#\" class=\"nav-link px-2 link-secondary\">Home</a></li>\n");
      out.write("		<li><a href=\"#\" class=\"nav-link px-2 link-dark\">브랜드</a></li>\n");
      out.write("		<li><a href=\"#\" class=\"nav-link px-2 link-dark\">카테고리</a></li>\n");
      out.write("		<li><a href=\"#\" class=\"nav-link px-2 link-dark\">상품검색</a></li>\n");
      out.write("	</ul>\n");
      out.write(" \n");
      out.write("	<div class=\"col-md-4 text-end\">\n");
      out.write("		<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id==null }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("			<form name=\"loginbtn\" method=\"post\">\n");
      out.write("				<input type=\"button\" class=\"btn btn-outline-dark me-2\"\n");
      out.write("					onclick=\"login()\" value=\"Log in\"> <input type=\"button\"\n");
      out.write("					class=\"btn btn-dark me-2\" onclick=\"signup()\" value=\"Sign Up\">\n");
      out.write("			</form>\n");
      out.write("		</c:if>\n");
      out.write("		");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("</header>");
      out.write("\n");
      out.write("\n");
      out.write("	<header class=\"site-header sticky-top py-1\">\n");
      out.write("		<nav\n");
      out.write("			class=\"container d-flex flex-column flex-md-row justify-content-between\">\n");
      out.write("			<a class=\"py-2\" href=\"#\" aria-label=\"Product\"> <svg\n");
      out.write("					xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\"\n");
      out.write("					fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\"\n");
      out.write("					stroke-linejoin=\"round\" stroke-width=\"2\" class=\"d-block mx-auto\"\n");
      out.write("					role=\"img\" viewBox=\"0 0 24 24\">\n");
      out.write("					<title>Product</title><circle cx=\"12\" cy=\"12\" r=\"10\" />\n");
      out.write("					<path\n");
      out.write("						d=\"M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94\" /></svg>\n");
      out.write("			</a> <a class=\"py-2 d-none d-md-inline-block\" href=\"#\">Tour</a> <a\n");
      out.write("				class=\"py-2 d-none d-md-inline-block\" href=\"#\">Product</a> <a\n");
      out.write("				class=\"py-2 d-none d-md-inline-block\" href=\"#\">Features</a> <a\n");
      out.write("				class=\"py-2 d-none d-md-inline-block\" href=\"#\">Enterprise</a> <a\n");
      out.write("				class=\"py-2 d-none d-md-inline-block\" href=\"#\">Support</a> <a\n");
      out.write("				class=\"py-2 d-none d-md-inline-block\" href=\"#\">Pricing</a> <a\n");
      out.write("				class=\"py-2 d-none d-md-inline-block\" href=\"#\">Cart</a>\n");
      out.write("		</nav>\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("	<main>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("					<img\n");
      out.write("						src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfMjIw%2FMDAxNjY2MzQ4OTQ4NDg3.fWdRpkHTF9zzR1wq4iz2kzUWZ8N3GkltTZPt6o3nzsog.B3Agi7jarn_RmJLYWuFAro-bbC7Z09fqRZe4-lxSEyMg.JPEG.heayoung0105%2F%25B4%25D9%25BF%25EE%25B7%25CE%25B5%25E5%25C6%25C4%25C0%25CF%25A3%25DF20221021%25A3%25DF194225.jpg&type=sc960_832\"\n");
      out.write("						class=\"card-img-top\" alt=\"...\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<p class=\"card-text\" align=\"center\">Nike Air Jordan 1</p>\n");
      out.write("						<p class=\"card-text\" align=\"center\">price : 400000₩</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("					<img\n");
      out.write("						src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfMjIw%2FMDAxNjY2MzQ4OTQ4NDg3.fWdRpkHTF9zzR1wq4iz2kzUWZ8N3GkltTZPt6o3nzsog.B3Agi7jarn_RmJLYWuFAro-bbC7Z09fqRZe4-lxSEyMg.JPEG.heayoung0105%2F%25B4%25D9%25BF%25EE%25B7%25CE%25B5%25E5%25C6%25C4%25C0%25CF%25A3%25DF20221021%25A3%25DF194225.jpg&type=sc960_832\"\n");
      out.write("						class=\"card-img-top\" alt=\"...\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<p class=\"card-text\" align=\"center\">Nike Air Jordan 1</p>\n");
      out.write("						<p class=\"card-text\" align=\"center\">price : 400000₩</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("					<img\n");
      out.write("						src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfMjIw%2FMDAxNjY2MzQ4OTQ4NDg3.fWdRpkHTF9zzR1wq4iz2kzUWZ8N3GkltTZPt6o3nzsog.B3Agi7jarn_RmJLYWuFAro-bbC7Z09fqRZe4-lxSEyMg.JPEG.heayoung0105%2F%25B4%25D9%25BF%25EE%25B7%25CE%25B5%25E5%25C6%25C4%25C0%25CF%25A3%25DF20221021%25A3%25DF194225.jpg&type=sc960_832\"\n");
      out.write("						class=\"card-img-top\" alt=\"...\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<p class=\"card-text\" align=\"center\">Nike Air Jordan 1</p>\n");
      out.write("						<p class=\"card-text\" align=\"center\">price : 400000₩</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("					<img\n");
      out.write("						src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfMjIw%2FMDAxNjY2MzQ4OTQ4NDg3.fWdRpkHTF9zzR1wq4iz2kzUWZ8N3GkltTZPt6o3nzsog.B3Agi7jarn_RmJLYWuFAro-bbC7Z09fqRZe4-lxSEyMg.JPEG.heayoung0105%2F%25B4%25D9%25BF%25EE%25B7%25CE%25B5%25E5%25C6%25C4%25C0%25CF%25A3%25DF20221021%25A3%25DF194225.jpg&type=sc960_832\"\n");
      out.write("						class=\"card-img-top\" alt=\"...\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<p class=\"card-text\" align=\"center\">Nike Air Jordan 1</p>\n");
      out.write("						<p class=\"card-text\" align=\"center\">price : 400000₩</p>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("					<img\n");
      out.write("						src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfMjIw%2FMDAxNjY2MzQ4OTQ4NDg3.fWdRpkHTF9zzR1wq4iz2kzUWZ8N3GkltTZPt6o3nzsog.B3Agi7jarn_RmJLYWuFAro-bbC7Z09fqRZe4-lxSEyMg.JPEG.heayoung0105%2F%25B4%25D9%25BF%25EE%25B7%25CE%25B5%25E5%25C6%25C4%25C0%25CF%25A3%25DF20221021%25A3%25DF194225.jpg&type=sc960_832\"\n");
      out.write("						class=\"card-img-top\" alt=\"...\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<p class=\"card-text\" align=\"center\">Nike Air Jordan 1</p>\n");
      out.write("						<p class=\"card-text\" align=\"center\">price : 400000₩</p>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"card\" style=\"width: 15rem;\">\n");
      out.write("					<img\n");
      out.write("						src=\"https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjEwMjFfMjIw%2FMDAxNjY2MzQ4OTQ4NDg3.fWdRpkHTF9zzR1wq4iz2kzUWZ8N3GkltTZPt6o3nzsog.B3Agi7jarn_RmJLYWuFAro-bbC7Z09fqRZe4-lxSEyMg.JPEG.heayoung0105%2F%25B4%25D9%25BF%25EE%25B7%25CE%25B5%25E5%25C6%25C4%25C0%25CF%25A3%25DF20221021%25A3%25DF194225.jpg&type=sc960_832\"\n");
      out.write("						class=\"card-img-top\" alt=\"...\">\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<p class=\"card-text\" align=\"center\">Nike Air Jordan 1</p>\n");
      out.write("						<p class=\"card-text\" align=\"center\">price : 400000₩</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<footer class=\"container py-5\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-12 col-md\">\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\"\n");
      out.write("					fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\"\n");
      out.write("					stroke-linejoin=\"round\" stroke-width=\"2\" class=\"d-block mb-2\"\n");
      out.write("					role=\"img\" viewBox=\"0 0 24 24\">\n");
      out.write("					<title>Product</title><circle cx=\"12\" cy=\"12\" r=\"10\" />\n");
      out.write("					<path\n");
      out.write("						d=\"M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94\" /></svg>\n");
      out.write("				<small class=\"d-block mb-3 text-muted\">&copy; 2017–2022</small>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-6 col-md\">\n");
      out.write("				<h5>Features</h5>\n");
      out.write("				<ul class=\"list-unstyled text-small\">\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Cool stuff</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Random feature</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Team feature</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Stuff for\n");
      out.write("							developers</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Another one</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Last time</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-6 col-md\">\n");
      out.write("				<h5>Resources</h5>\n");
      out.write("				<ul class=\"list-unstyled text-small\">\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Resource name</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Resource</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Another resource</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Final resource</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-6 col-md\">\n");
      out.write("				<h5>Resources</h5>\n");
      out.write("				<ul class=\"list-unstyled text-small\">\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Business</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Education</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Government</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Gaming</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-6 col-md\">\n");
      out.write("				<h5>About</h5>\n");
      out.write("				<ul class=\"list-unstyled text-small\">\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Team</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Locations</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Privacy</a></li>\n");
      out.write("					<li><a class=\"link-secondary\" href=\"#\">Terms</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"/docs/5.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
